title: Python Crash Course, 2nd Edition
description: Online Resources for Python Crash Course, from No Starch Press
baseurl: "/pcc_2e"
url: "https://mavjav-edu.github.io"
logo: "assets/images/pcc_logo_csyivv_c_scale,w_788.png"
permalink: pretty
exclude: ["vendor/", "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile","normalize.scss.md",".vscode/*","rollup.config.js", "docs/tests/"]

timezone: America/Vancouver
language: en-CA
lang_direction: ltr

search_enabled: true

aux_links:
  "Python Crash Course on GitHub":
    - "//github.com/mavjav-edu/pcc_2e"

relative_links:
  enabled:     true
  collections: false


color_scheme: dark
theme_color: "#e6e1e8"
theme_background_color: "#27262b"

ga_tracking: G-H1B6T2W9DJ

plugins:
  - jekyll-seo-tag
  - jekyll-relative-links